// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_chirp.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteChirp = `-- name: DeleteChirp :one
WITH deletedRows AS (
    DELETE FROM chirps AS c
    WHERE c.id = $1 AND c.user_id = $2 
    RETURNING id, created_at, updated_at, user_id, body
) 
SELECT chirps.id, chirps.created_at, chirps.updated_at, chirps.user_id, chirps.body, (SELECT COUNT(*) FROM deletedRows) AS deletedCt 
FROM chirps 
WHERE chirps.id = $1
`

type DeleteChirpParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type DeleteChirpRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	Body      string
	Deletedct int64
}

func (q *Queries) DeleteChirp(ctx context.Context, arg DeleteChirpParams) (DeleteChirpRow, error) {
	row := q.db.QueryRowContext(ctx, deleteChirp, arg.ID, arg.UserID)
	var i DeleteChirpRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Body,
		&i.Deletedct,
	)
	return i, err
}
