// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fetch_all_chirps_by_author.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const fetchAllChirpsByAuthor = `-- name: FetchAllChirpsByAuthor :many
SELECT id, created_at, updated_at, user_id, body FROM chirps WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) FetchAllChirpsByAuthor(ctx context.Context, userID uuid.UUID) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, fetchAllChirpsByAuthor, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
