// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upgrade_to_chirpy_red.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateChirpyRedStatus = `-- name: UpdateChirpyRedStatus :one
UPDATE users SET is_chirpy_red = $2 WHERE id = $1 RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type UpdateChirpyRedStatusParams struct {
	ID          uuid.UUID
	IsChirpyRed bool
}

func (q *Queries) UpdateChirpyRedStatus(ctx context.Context, arg UpdateChirpyRedStatusParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateChirpyRedStatus, arg.ID, arg.IsChirpyRed)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}
